// Mocks generated by Mockito 5.4.2 from annotations
// in smart_calculator/test/domain/calculate_answer_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:smart_calculator/domain/model/input_model.dart' as _i3;
import 'package:smart_calculator/domain/usecase/validate_input_usecase.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ValidateInputUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockValidateInputUseCase extends _i1.Mock
    implements _i2.ValidateInputUseCase {
  MockValidateInputUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool call(_i3.InputModel? params) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: false,
      ) as bool);
}
